### ISSUE TITLE
How to open/use?

### ISSUE THREAD

**Issue by GiacoBu** [UniversalDependencies/UD_Icelandic-IcePaHC#3]
I am very new to UDs and I don't know how to open/use this, is there a specific program I need for visualization? Thanks in advance

**Comment by dan-zeman** [comment]
It depends on what you want to use it for. If you want to search for particular linguistic phenomena and visualize the dependency trees that contain them, you may want to use one of the UD tree search engines, [such as this one](http://hdl.handle.net/11346/PMLTQ-RM2F).

**Comment by AngledLuffa** [comment]
Close issue?

Could also tells us more about what you need if that didn't solve your problem.
